[package]
name = "ublox-short-range-rs"
version = "0.0.1"
authors = ["Mathias Koch <mk@blackbird.online>"]
description = "Driver crate for u-blox short range devices, implementation follows 'UBX-14044127 - R40'"
readme = "README.md"
keywords = ["arm", "cortex-m", "ublox", "wifi", "shortrange", "bluetooth"]
categories = ["embedded", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/BlackbirdHQ/ublox-short-range-rs"
edition = "2018"

[lib]
name = "ublox_short_range"
doctest = false

[dependencies]
heapless = "0.5.1"
no-std-net = "0.2.3"
embedded-hal = "0.2.3"
nb = "0.1.2"
at-rs = "0.0.7"

[dependencies.log]
version = "0.4"
default-features = false

[dependencies.packed_struct_codegen]
version = "0.3"
default-features = false

[dependencies.packed_struct]
version = "0.3"
default-features = false

[dev-dependencies]
env_logger = "0.7.1"
void = "1.0.2"
linux-embedded-hal = "0.3.0"
serial = "0.4.0"

[patch.crates-io]
at-rs = { path="../at-rs" }

[features]
default = ["odin_w2xx", "wifi_ap", "wifi_sta", "socket-tcp"]

odin_w2xx = []
nina_w1xx = []
nina_b1xx = []
anna_b1xx = []
nina_b2xx = []
nina_b3xx = []

socket-tcp = []

wifi_ap = []
wifi_sta = []
bluetooth = []
