[package]
name = "ublox-short-range-rs"
version = "0.0.1"
authors = ["Mathias Koch <mk@blackbird.online>"]
description = "Driver crate for u-blox short range devices, implementation follows 'UBX-14044127 - R40'"
readme = "README.md"
keywords = ["arm", "cortex-m", "ublox", "wifi", "shortrange", "bluetooth"]
categories = ["embedded", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/BlackbirdHQ/ublox-short-range-rs"
edition = "2021"

[lib]
name = "ublox_short_range"
doctest = false

[dependencies]
heapless = { version = "^0.5", features = ["serde"] }
no-std-net = { version = "0.4.0", features = ["serde"] }
nb = "0.1.2"
serde = { version = "^1", default-features = false, features = ["derive"] }
typenum = "^1"
atat = "^0.8.4"
defmt = "0.1"
embedded-hal = { version = "1.0.0-alpha.4" }
embedded-nal = "0.2.0"

[dependencies.packed_struct]
version = "0.3"
default-features = false

[dependencies.packed_struct_codegen]
version = "0.3"
default-features = false

[dev-dependencies]
env_logger = "0.7.1"
void = "1.0.2"
linux-embedded-hal = "0.3.0"
serial = "0.4.0"

[features]
default = ["odin_w2xx", "wifi_ap", "wifi_sta", "socket-udp", "socket-tcp"]

odin_w2xx = []
nina_w1xx = []
nina_b1xx = []
anna_b1xx = []
nina_b2xx = []
nina_b3xx = []

socket-tcp = []
socket-udp = []
# logging = ["defmt"]

defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []

wifi_ap = []
wifi_sta = []
bluetooth = []
